/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author maja
 */
public class Prozor extends javax.swing.JFrame {
    public double cijena;
    public BigDecimal rez;
    public BigDecimal rez2;
    public double ukupnaCijena;
    public double pdv;
    public double rabat;
    public int kolicina;
    DecimalFormat df= new DecimalFormat("#.###");
    
    public Prozor() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        izracunaj1 = new javax.swing.JButton();
        kolicina_1 = new javax.swing.JTextField();
        cijena_1 = new javax.swing.JTextField();
        rezultat_1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rabat1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pdv1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labela1 = new javax.swing.JLabel();
        labela2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izračun cijene s rabatom i PDV-om");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Količina ");

        jLabel12.setText("Cijena primjerka");

        izracunaj1.setText("Izračunaj!");
        izracunaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izracunaj1ActionPerformed(evt);
            }
        });

        kolicina_1.setText("1");
        kolicina_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolicina_1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Rabat %");

        jLabel15.setText("PDV %");

        pdv1.setText("5");
        pdv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdv1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rezultat_1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kolicina_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cijena_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rabat1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pdv1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(izracunaj1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rezultat_1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kolicina_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cijena_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pdv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izracunaj1))
                .addGap(294, 294, 294))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labela2)
                    .addComponent(labela1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(labela1)
                .addGap(35, 35, 35)
                .addComponent(labela2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izracunaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izracunaj1ActionPerformed
        kontrola();
        izracunaj();
       
        
        
    }//GEN-LAST:event_izracunaj1ActionPerformed

    private void pdv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdv1ActionPerformed

    private void kolicina_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolicina_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolicina_1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cijena_1;
    private javax.swing.JButton izracunaj1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kolicina_1;
    private javax.swing.JLabel labela1;
    private javax.swing.JLabel labela2;
    private javax.swing.JTextField pdv1;
    private javax.swing.JTextField rabat1;
    private javax.swing.JLabel rezultat_1;
    // End of variables declaration//GEN-END:variables

    private void kontrola() {
        
         if(cijena_1.getText().trim().length()==0 ){
            JOptionPane.showMessageDialog(rootPane,"Morate unijeti cijenu primjerka","Upozorenje",JOptionPane.WARNING_MESSAGE);
        return;
        } 
         if(kolicina_1.getText()==null){
            JOptionPane.showMessageDialog(rootPane,"Morate unijeti količinu primjerka","Upozorenje",JOptionPane.WARNING_MESSAGE);
        return;
        } 
         try {
            kolicina=Integer.parseInt(kolicina_1.getText());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"Količina mora biti cijeli broj","Pogreška",JOptionPane.ERROR_MESSAGE);
            this.kolicina_1.requestFocus();
            return;
        }
         
        try {
            double r=Double.parseDouble(rabat1.getText());
            rabat=(100-r)/100;
            
            labela2.setText(String.valueOf(rabat));
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"Rabat mora biti broj","Pogreška",JOptionPane.ERROR_MESSAGE);
            this.rabat1.requestFocus();
            return;
        }
        try {
           double p=Double.parseDouble(pdv1.getText());
            pdv=(100+p)/100;
            labela2.setText(String.valueOf(pdv));
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"PDV mora biti broj","Pogreška",JOptionPane.ERROR_MESSAGE);
            this.pdv1.requestFocus();
        }
    }

    private void izracunaj() {
        if(cijena_1.getText().trim().length()!=0){
            try {
            cijena=Double.parseDouble(cijena_1.getText());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane,"Cijena mora biti broj","Pogreška",JOptionPane.ERROR_MESSAGE);
            this.cijena_1.requestFocus();
        }
        double rez= cijena*rabat*pdv;
        
        labela1.setText( "Cijena jednog primjerka je: " + df.format(rez));
        
        double rez2= cijena*rabat*pdv*kolicina;
        rez2= Math.round(rez2);
        labela2.setText( "Ukupna cijena je: " + df.format(rez2)); 
        
        } 
    }
}
